#apiVersion: v1
#kind: Namespace
#metadata:
#  name: server
#        command: [ "/bin/sh", "-c", "ls /etc/nginx/" ]
--- 

apiVersion: v1
kind: ConfigMap
metadata:
#  labels:
#    app: nginx
  name: nginx-configmap
  namespace: default
data:
  nginx.conf:
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    events {
    worker_connections  1024;
    }
    http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    server {
    listen 80;    
    location = /status {
    access_log off;
    default_type text/plain;
    add_header Content-Type text/plain;
    return 200 "alive";
    }
    location / {
    gzip off;
    root /usr/share/nginx/html/;
    index  index.html;
    }
    location /example/ {
    proxy_pass http://example.com/ ;
    }
    location ~* \.(js|jpg|png|css)$ {
    root /usr/share/nginx/html/;
    }
    } 
    sendfile on;
    keepalive_timeout  65;
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: config-volume
          configMap: 
            name: nginx-configmap
      containers:
        - name: nginx
          image: nginx:1.15.8-alpine
          # command: ["sleep", "5000"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      restartPolicy: Always


--- 

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

